version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - D:\zookeeper\data:/data
    ports:
      - "2181:2181"
       
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_MESSAGE_MAX_BYTES: 2000000
      KAFKA_CREATE_TOPICS: "Topic1:1:1,Topic2:1:1:compact"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - D:\kafka\kafka-logs:/kafka
      - D:\kafka\run\docker.sock:/var/run/docker.sock
 
  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9020:9000
    environment:
      ZK_HOSTS: zookeeper:2181

  redis:
    image: redis
    volumes:
      - D:\redis\data:/data
    ports:
      - 6379:6379